fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
#    inifile: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
  symlinks:
    teamspeak3: '#{source_dir}'

