name          'jbouse-teamspeak3'
version       '0.1.0'
source        'git@github.com:UGNS/puppet-teamspeak3.git'
author        'jbouse'
license       'Apache License, Version 2.0'
summary       ' TeamSpeak3 communication system puppet module'
description   ' TeamSpeak3 communication system - http://teamspeak.com/?page=teamspeak3'
project_page  'https://github.com/UGNS/puppet-teamspeak3'

dependency 'puppetlabs/stdlib', '>= 2.1.0'
dependency 'nanliu/staging', '>= 0.3.1'
